"""Add interview progress tracking

Revision ID: 67c8e1fac1d6
Revises: b6a0f68e52c5
Create Date: 2026-08-30 11:06:13.514179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c8e1fac1d6'
down_revision: Union[str, Sequence[str], None] = 'b6a0f68e52c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('status', sa.String(), nullable=False))
    op.add_column('interviews', sa.Column('current_question_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'current_question_index')
    op.drop_column('interviews', 'status')
    # ### end Alembic commands ###
