"""Store interview questions as JSON

Revision ID: 6fc7000b1c3a
Revises: fa7242819ec5
Create Date: 2026-08-13 22:54:21.282302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc7000b1c3a'
down_revision: Union[str, Sequence[str], None] = 'fa7242819ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "interviews",
        "questions",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="questions::json")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "interviews",
        "questions",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=False,
        postgresql_using="questions::text")
    # ### end Alembic commands ###
